In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")

data_x = pd.read_excel("D:\KESHE\keshe\gprj\mathmatical-2021\第一问\原始数据\Molecular-200.xlsx")
data_y = pd.read_excel("D:\KESHE\keshe\gprj\mathmatical-2021\第一问\原始数据\ER-200.xlsx")
head_data = pd.read_excel("D:\KESHE\keshe\gprj\mathmatical-2021\第一问\已处理数据\随机森林回归模型重要参数选择指数.xlsx")
head_data = head_data['特征名称'][:21]
head2list = []

for i in head_data:
    head2list.append(i)

data_x = data_x.iloc[0:,1:]
print(data_x.shape)
data_y = data_y['IC50_nM']
data_k = data_x[head2list]
print("data_k:",data_k.shape)
# data_x = data_x.drop(head2list, axis=1)
print(data_x.shape)

(72, 729)
data_k: (72, 21)
(72, 729)


In [48]:
from sklearn.externals import joblib
model = joblib.load("D:\\KESHE\\keshe\gprj\\mathmatical-2021\\第二问\\model.pkl")
a = model.predict(data_k)

In [59]:
data_x['label'] = a

data_x = data_x.sort_values(by="label" , ascending=False)
data_h = data_x.head()
# data_h = data_h[head2list]
# by 指定列 ascending
data_h.head


<bound method NDFrame.head of     nAcid   ALogP    ALogp2       AMR       apol  naAromAtom  nAromBond  \
29      0  2.1136  4.467305  142.4650  71.936204          18         18   
65      0  1.9798  3.919608   91.2618  46.619860          12         12   
20      0 -0.0304  0.000924  130.5706  77.263755          12         12   
44      0  1.4743  2.173560  146.1048  76.162997          18         18   
66      0  0.8955  0.801920  152.6685  80.872169          23         26   

    nAtom  nHeavyAtom  nH   ...        WTPT-1    WTPT-2     WTPT-3     WTPT-4  \
29     60          32  28   ...     66.637710  2.082428  18.341363   8.297882   
65     40          20  20   ...     39.997873  1.999894   5.042818   5.042818   
20     67          32  35   ...     66.767621  2.086488  15.463198   8.856322   
44     62          33  29   ...     68.748923  2.083301  18.011114   8.171676   
66     69          36  33   ...     74.517708  2.069936  14.780783  11.374138   

      WTPT-5  WPATH  WPOL  XLogP

In [60]:
data_h = data_h.drop("label",axis=1)
model_XGBR = joblib.load("D:\\KESHE\\keshe\\gprj\\mathmatical-2021\\第三问\\model_XGBR.pkl")
model_AdaBR = joblib.load("D:\\KESHE\\keshe\\gprj\\mathmatical-2021\\第三问\\model_AdaBR.pkl")
model_RFR = joblib.load("D:\\KESHE\\keshe\\gprj\\mathmatical-2021\\第三问\\model_RFR.pkl")
model_svc = joblib.load("D:\\KESHE\\keshe\\gprj\\mathmatical-2021\\第三问\\model_svc.pkl")
model_knn = joblib.load("D:\\KESHE\\keshe\\gprj\\mathmatical-2021\\第三问\\model_knn.pkl")

In [63]:


XGBR = model_XGBR.predict(data_h)
AdaBR = model_AdaBR.predict(data_h)
RFR = model_RFR.predict(data_h)
svc = model_svc.predict(data_h)
knn = model_knn.predict(data_h)
print(XGBR)
print(AdaBR)
print(RFR)
print(svc)
print(knn)

[1 0 1 1 1]
[0 0 0 0 0]
[1 0 1 1 1]
[0 1 0 0 0]
[1 1 0 1 1]


In [ ]:
from sklearn import preprocessing

# 方案2